"""
FastAPI service for story generation.
Converts topic + narrator into complete illustrated story.
"""

import json
import uuid
from typing import Optional
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from models.story_models import (
    Story, StoryGenerationRequest, StoryGenerationResponse,
    Narrator, StoryPage, CYUItem, StoryContext
)
from services.gemini_client import generate_story_json, generate_image
from services.prompt_builder import build_educational_story_prompt, build_image_prompt
from services.storage import upload_to_cloudinary

app = FastAPI(title="educ-ATE Story Generation Service", version="1.0.0")

# CORS for TypeScript backend communication
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3001"],  # TypeScript backend
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/generate-story", response_model=StoryGenerationResponse)
async def generate_story(request: StoryGenerationRequest):
    """
    Generate complete illustrated story with all branches.
    Images generated in parallel, audio handled by voice agents.
    """
    try:
        story_id = f"story_{uuid.uuid4().hex[:8]}"

        # 1. Generate story structure with Gemini
        story_context = StoryContext(
            topic=request.topic,
            current_page="",
            story_so_far="",
            narrator_character=request.narrator.character,
            educational_facts_covered=[],
            adhd_mode=True
        )

        story_prompt = build_educational_story_prompt(request.topic, request.narrator, story_context)
        raw_json = generate_story_json(story_prompt)

        try:
            story_data = json.loads(raw_json)
        except json.JSONDecodeError:
            raise HTTPException(status_code=500, detail="Invalid JSON from Gemini")

        # 2. Convert to our Story model
        story = convert_to_story_model(story_data, story_id, request.topic, request.narrator)

        # 3. Generate all images in parallel
        await generate_all_images(story)

        return StoryGenerationResponse(
            story_id=story_id,
            status="completed",
            story=story,
            message="Story generated successfully!"
        )

    except Exception as e:
        print(f"Story generation error: {e}")
        return StoryGenerationResponse(
            story_id=story_id if 'story_id' in locals() else "unknown",
            status="failed",
            message=f"Failed to generate story: {str(e)}"
        )

async def generate_all_images(story: Story):
    """Generate images for all pages including branches"""
    import asyncio

    # Collect all pages (trunk + branches)
    all_pages = story.pages.copy()
    for page in story.pages:
        if page.choice:
            all_pages.extend(page.choice.option_a.pages)
            all_pages.extend(page.choice.option_b.pages)

    # Generate all images in parallel
    tasks = []
    for page in all_pages:
        if page.image_prompt:
            task = generate_page_image(page)
            tasks.append(task)

    await asyncio.gather(*tasks, return_exceptions=True)

async def generate_page_image(page: StoryPage):
    """Generate and upload image for a single page"""
    try:
        # Build enhanced image prompt
        prompt = build_image_prompt(page.image_prompt)
        print(f"Generating image for page {page.page_id}...")

        # Generate image with Gemini
        image = generate_image(prompt)
        if image is None:
            print(f"Failed to generate image for page {page.page_id}")
            return

        # Upload to Cloudinary
        image_url = upload_to_cloudinary(image, page.page_id)
        page.image_url = image_url

        print(f"✓ Generated image for page {page.page_id}")

    except Exception as e:
        print(f"Error generating image for page {page.page_id}: {e}")

def convert_to_story_model(gemini_data: dict, story_id: str, topic: str, narrator: Narrator) -> Story:
    """Convert Gemini response to our Story model"""
    # This is a simplified conversion - you'll need to map Gemini's format to your Story schema
    # For now, using the existing fake story structure as template

    pages = []
    if "scenes" in gemini_data:
        for i, scene in enumerate(gemini_data["scenes"]):
            page = StoryPage(
                page_id=f"p{i+1}",
                narration=scene.get("text", ""),
                image_prompt=scene.get("visual", {}).get("setting", ""),
                image_url="",  # Will be populated by image generation
                audio_url="",  # Handled by voice agents
                hotspots=[],   # TODO: Could be generated by Gemini too
                choice=None    # TODO: Add branching logic
            )
            pages.append(page)

    # Add some CYU items
    cyu_items = [
        CYUItem(type="voice", question=f"What did you learn about {topic}?"),
        CYUItem(type="draw", question=f"Draw what you think a {topic} looks like!")
    ]

    return Story(
        id=story_id,
        title=gemini_data.get("title", f"Learning About {topic.title()}"),
        topic=topic,
        narrator=narrator,
        pages=pages,
        cyu=cyu_items
    )

@app.get("/health")
async def health_check():
    return {"status": "healthy", "service": "story-generation"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)